linters:
  phpcs:
    standard: PSR2
    fixer: true
  csslint: {  }
  shellcheck:
    shell: bash
  rubocop:
    display_cop_names: true
    fixer: true
files:
  ignore:
    - 'vendor/*'
    - 'bower_components/*'
fixers:
  enable: true
