linters:
    phpcs:
        standard: PSR2
        fixer: true
    eslint:
        config: eslint.json
        fixer: true
    rubocop:
        display_cop_names: true
        fixer: true
    flake8:
    eslint:
        config: './eslint.config'
    checkstyle:
        config: ./checkstyle.xml
    shellcheck:
        shell: bash
        exclude: 'SC2154,SC2069'

files:
    ignore:
        - 'src/generated/*'
        - 'webroot/bower_components/*'
        

